import express from 'express';
import cors from 'cors';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import multer from 'multer';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3001;

app.use(cors({ origin: 'http://localhost:5173' }));
app.use(express.json());

// Path to the ATS json database
const JSON_PATH = path.resolve(__dirname, '..', 'ats_backend_system', 'candidates_data.json');

// ── Paths for the Python Execution Bridge ─────────────────────────────────
const ATS_DIR = path.resolve(__dirname, '..', 'ats_backend_system');
const UPLOAD_DIR = path.resolve(ATS_DIR, 'resumes_to_process');
const PYTHON_EXE = path.resolve(ATS_DIR, 'venv', 'Scripts', 'python.exe');

// Ensure the target directory exists
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

const storage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, UPLOAD_DIR),
  filename: (_req, file, cb) => cb(null, file.originalname),
});

const upload = multer({
  storage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB per file
  fileFilter: (_req, file, cb) => {
    const allowed = ['.pdf', '.png', '.jpg', '.jpeg'];
    const ext = path.extname(file.originalname).toLowerCase();
    if (allowed.includes(ext)) {
      cb(null, true);
    } else {
      cb(new Error(`Unsupported file type: ${ext}`));
    }
  },
});

/**
 * POST /api/upload
 * 1. Accepts multipart/form-data → saves files to resumes_to_process/
 * 2. Runs `python main.py` (OCR + AI extraction)
 * 3. Runs `python export_results.py` (CSV export)
 * 4. Returns 200 only after both scripts complete
 */
// Precompute env with UTF-8 so Python emojis don't crash on Windows cp1252
const PYTHON_ENV = { ...process.env, PYTHONIOENCODING: 'utf-8', PYTHONUTF8: '1' };

app.post('/api/upload', upload.array('files', 50), async (req, res) => {
  const uploadedFiles = (req.files || []).map((f) => f.originalname);

  try {
    console.log(`\n📁 ${uploadedFiles.length} file(s) saved: ${uploadedFiles.join(', ')}`);

    // ── Step 1: Run main.py (OCR, NLP, CV, scoring) ──
    console.log('🧠 Running main.py (AI Processing)...');
    const { stdout: mainOut, stderr: mainErr } = await execAsync(
      `"${PYTHON_EXE}" main.py`,
      { cwd: ATS_DIR, timeout: 120_000, env: PYTHON_ENV }   // 2-minute timeout
    );
    if (mainOut) console.log(mainOut);
    if (mainErr) console.warn('main.py stderr:', mainErr);

    // ── Step 2: Run export_results.py ──
    console.log('📊 Running export_results.py...');
    const { stdout: expOut, stderr: expErr } = await execAsync(
      `"${PYTHON_EXE}" export_results.py`,
      { cwd: ATS_DIR, timeout: 30_000, env: PYTHON_ENV }
    );
    if (expOut) console.log(expOut);
    if (expErr) console.warn('export_results.py stderr:', expErr);

    console.log('✅ Pipeline finished successfully.\n');

    res.json({
      success: true,
      message: `${uploadedFiles.length} resume(s) processed by AI pipeline.`,
      files: uploadedFiles,
    });
  } catch (err) {
    console.error('❌ Python pipeline error:', err.message);
    // Still return the files that were saved so the user knows
    res.status(500).json({
      success: false,
      error: `Python pipeline failed: ${err.message}`,
      files: uploadedFiles,
    });
  }
});

/**
 * GET /api/download-csv
 * Serves the vishesh_report.csv generated by export_results.py
 */
app.get('/api/download-csv', (req, res) => {
  const csvPath = path.resolve(ATS_DIR, 'vishesh_report.csv');
  if (!fs.existsSync(csvPath)) {
    return res.status(404).json({ error: 'CSV report not found. Upload and process resumes first.' });
  }
  res.download(csvPath, 'candidates_report.csv');
});

/**
 * GET /api/candidates
 */
app.get('/api/candidates', (req, res) => {
  try {
    if (!fs.existsSync(JSON_PATH)) {
      return res.json({ candidates: [] });
    }
    const data = fs.readFileSync(JSON_PATH, 'utf-8');
    let candidates = JSON.parse(data);

    // Sort by match_score DESC (default to 0 if missing)
    candidates.sort((a, b) => (b.match_score || 0) - (a.match_score || 0));

    const parsed = candidates.map((c) => ({
      ...c,
      skills: Array.isArray(c.skills) ? c.skills : (typeof c.skills === 'string' ? (() => { try { return JSON.parse(c.skills || '[]'); } catch { return []; } })() : []),
      experience: Array.isArray(c.experience) ? c.experience[0] : (c.experience || 'Fresher')
    }));

    res.json({ candidates: parsed });
  } catch (err) {
    console.error('JSON data error:', err.message);
    res.status(500).json({ error: 'Failed to read candidates', detail: err.message });
  }
});

/**
 * GET /api/system-status
 */
app.get('/api/system-status', (req, res) => {
  try {
    const exists = fs.existsSync(JSON_PATH);
    if (!exists) {
      return res.json({ online: false, message: 'JSON file not found', candidateCount: 0 });
    }

    const data = fs.readFileSync(JSON_PATH, 'utf-8');
    const candidates = JSON.parse(data);
    const count = candidates.length;

    res.json({
      online: true,
      message: `System Online: ${count} Candidates Indexed`,
      candidateCount: count,
    });
  } catch (err) {
    console.error('System status error:', err.message);
    res.json({ online: false, message: `Error: ${err.message}`, candidateCount: 0 });
  }
});

/**
 * In-memory jobs store (mock persistence)
 */
let jobsStore = [
  { id: "1", title: "Senior Frontend Developer", department: "Engineering", status: "Active", type: "Full-time", location: "Remote", applicants: 45, postedDate: "2 days ago" },
  { id: "2", title: "Product Marketing Manager", department: "Marketing", status: "Draft", type: "Contract", location: "Hybrid", applicants: 0, postedDate: "1 hour ago" },
  { id: "3", title: "UX/UI Designer", department: "Design", status: "Closed", type: "Full-time", location: "Remote", applicants: 112, postedDate: "14 days ago" },
];

/**
 * GET /api/jobs
 */
app.get('/api/jobs', (req, res) => {
  res.json({ jobs: jobsStore });
});

/**
 * POST /api/jobs
 */
app.post('/api/jobs', (req, res) => {
  const job = {
    id: Date.now().toString(36),
    applicants: 0,
    postedDate: "Just now",
    status: "Active",
    type: "Full-time",
    department: "General",
    ...req.body,
  };
  jobsStore.unshift(job);
  res.status(201).json({ job });
});

app.listen(PORT, () => {
  console.log(`\n✅ ATS API server running at http://localhost:${PORT}`);
  console.log(`   Data source: ${JSON_PATH}\n`);
});
